#define TOKEN_LIST \
    X(TOKEN_NUMBER) \
    X(TOKEN_IDENTIFIER) \
    X(TOKEN_PLUS) \
    X(TOKEN_MINUS) \
    X(TOKEN_STAR) \
    X(TOKEN_SLASH) \
    X(TOKEN_POWER) \
    X(TOKEN_LPAREN) \
    X(TOKEN_RPAREN) \
    X(TOKEN_ASSIGN) \
    X(TOKEN_COMMA) \
    X(TOKEN_EQUAL) \
    X(TOKEN_NOT_EQUAL) \
    X(TOKEN_LESS) \
    X(TOKEN_LESS_EQUAL) \
    X(TOKEN_GREATER) \
    X(TOKEN_GREATER_EQUAL) \
    X(TOKEN_EOF) \
    X(TOKEN_UNKNOWN)
    